extends Node

var leftColor = Color.from_hsv(1,1,1)
var rightColor = Color.from_hsv(1,1,1)

var addedY = 0
var targetPosition

var oppositesJSON = "res://other/opposites.json"
var oppositesInfo
var oppositeNumber

# Initialize project by generating colors and opposites
func _ready():
	generateOpposites()
	randomColors()
	await get_tree().create_timer(0.05).timeout
	getHint()

# Generate a random color for each half of the card (the code Color.from_hsv(randf(), 1, 1) is taken from Copilot AI Summary)
func randomColors():
	leftColor = Color.from_hsv(round(randf()*32)/32, 1, 0.8)
	rightColor = Color.from_hsv(round(randf()*32)/32, 1, 0.8)
	
	$lefthalf.modulate = leftColor
	$righthalf.modulate = rightColor

# Detect when the mouse clicks and hide the card while the cover is open
func _input(event):
	if(event.is_action_pressed("click") and $"/root/Main/Board Cover".rotation_degrees == 0):
		for i in 50:
			addedY = ease(i/50.0, 0.3) * 220
			self.position.y = 500 + addedY
			
			await get_tree().create_timer(0.01).timeout
		
		randomColors()
		generateOpposites()
		
		await get_tree().create_timer(3.05).timeout
		
		getHint()
		for i in 50:
			addedY = 220 - ease(i/50.0, 0.3) * 220
			self.position.y = 500 + addedY
			
			await get_tree().create_timer(0.01).timeout

# Generate opposites from the JSON file (code generated by Microsoft Copilot and debugged/modified manually)
func generateOpposites():
	# Load the JSON file
	var file = FileAccess.open(oppositesJSON, FileAccess.READ)
	if file:
		var json_text = file.get_as_text()
		var data = JSON.parse_string(json_text)
		
		if typeof(data) == TYPE_DICTIONARY and data.has("opposites_list"):
			var opposites_list = data["opposites_list"]
			
			# Choose a random pair
			oppositeNumber = RandomNumberGenerator.new().randi_range(0, opposites_list.size()-1)
			oppositesInfo = opposites_list[oppositeNumber]
			
			$lefttext.text = oppositesInfo["left_side"]
			$righttext.text = oppositesInfo["right_side"]
			
			#print("Left side: " + oppositesInfo["left_side"])
			#print("Right side: " + oppositesInfo["right_side"])
			print("Number generated: " + str(oppositeNumber))
			#print(opposites_list.size())
		else:
			print("Invalid JSON structure.")
	else:
		print("Failed to open file.")

# Get the hint from the JSON file and apply it
func getHint():
	targetPosition = round($"/root/Main/Target".rotation_degrees / 1.8) + 50
	print(targetPosition)
	
	oppositesInfo = JSON.parse_string(
		FileAccess.open(oppositesJSON, FileAccess.READ).get_as_text()
	)["opposites_list"][oppositeNumber]
	print(oppositeNumber)
	
	if targetPosition > 80:
		$hint.text = oppositesInfo["right_hint"]
	else: if targetPosition > 60:
		$hint.text = oppositesInfo["mid_right_hint"]
	else: if targetPosition > 40:
		$hint.text = oppositesInfo["middle_hint"]
	else: if targetPosition > 20:
		$hint.text = oppositesInfo["mid_left_hint"]
	else:
		$hint.text = oppositesInfo["left_hint"]
	
	print($hint.text)
