extends Node

var leftColor = Color.from_hsv(1,1,1)
var rightColor = Color.from_hsv(1,1,1)

var addedY = 0

var oppositesJSON = "res://other/opposites.json"

# Initialize project by generating colors and opposites
func _ready():
	generateOpposites()
	
	randomColors()

# Generate a random color for each half of the card (the code Color.from_hsv(randf(), 1, 1) is taken from Copilot AI Summary)
func randomColors():
	leftColor = Color.from_hsv(randf(), 1, 0.8)
	rightColor = Color.from_hsv(randf(), 1, 0.8)
	
	$lefthalf.modulate = leftColor
	$righthalf.modulate = rightColor

# Detect when the mouse clicks and hide the card while the cover is open
func _input(event):
	if(event.is_action_pressed("click") and $"/root/Main/Board Cover".rotation_degrees == 0):
		for i in 50:
			addedY = ease(i/50.0, 0.3) * 220
			self.position.y = 500 + addedY
			
			await get_tree().create_timer(0.01).timeout
		randomColors()
		await get_tree().create_timer(3).timeout
		for i in 50:
			addedY = 220 - ease(i/50.0, 0.3) * 220
			self.position.y = 500 + addedY
			
			await get_tree().create_timer(0.01).timeout

# Generate opposites from the JSON file (code generated by Microsoft Copilot and debugged/modified manually)
func generateOpposites():
	# Load the JSON file
	var file = FileAccess.open(oppositesJSON, FileAccess.READ)
	if file:
		var json_text = file.get_as_text()
		var data = JSON.parse_string(json_text)
		
		if typeof(data) == TYPE_DICTIONARY and data.has("opposites_list"):
			var opposites_list = data["opposites_list"]
			
			# Choose a random pair
			var random_index = RandomNumberGenerator.new().randi_range(0, opposites_list.size()-1)
			var pair = opposites_list[random_index]
			
			$lefttext.text = pair["left_side"]
			$righttext.text = pair["right_side"]
			
			print("Left side: " + pair["left_side"])
			print("Right side: " + pair["right_side"])
			print("Number generated: " + str(random_index))
			print(pair)
		else:
			print("Invalid JSON structure.")
	else:
		print("Failed to open file.")
